language: node_js

node_js:
  - '10'

os:
  - linux

cache: npm

branches:
  only:
    - master

install:
  - npm install -g vsce
  - npm install

script:
  - vsce package

deploy:
  provider: releases
  file: "*.vsix"
  api_key: $GITHUB_API_KEY
  file_glob: true
  skip_cleanup: true
  draft: true
  overwrite: true